# Generated by Django 4.2.7 on 2025-11-23 11:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reel', 'verbose_name_plural': 'Reels'},
        ),
        migrations.RemoveField(
            model_name='reel',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='user',
        ),
        migrations.AddField(
            model_name='reel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reels', to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='reel',
            name='caption',
            field=models.TextField(blank=True, max_length=2200, verbose_name='Tavsif (Caption)'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(upload_to='reels/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Video Fayl'),
        ),
        migrations.CreateModel(
            name='ReelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Sharh matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reels.reelcomment')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reels.reel')),
            ],
            options={
                'verbose_name': 'Reel Sharhi',
                'verbose_name_plural': 'Reel Sharhlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reels.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reel Like',
                'verbose_name_plural': 'Reel Likes',
                'unique_together': {('reel', 'user')},
            },
        ),
    ]
