# Generated by Django 4.2.7 on 2025-11-23 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0002_alter_reel_options_remove_reel_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
    ]
