# Generated by Django 4.2.7 on 2025-11-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_instagrampost_options_instagrampost_post_type_and_more'),
        ('reels', '0003_alter_reel_created_at_alter_reel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reelcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reelcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reelcomment',
            name='reel',
        ),
        migrations.AlterUniqueTogether(
            name='reellike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reellike',
            name='reel',
        ),
        migrations.RemoveField(
            model_name='reellike',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reel',
        ),
        migrations.DeleteModel(
            name='ReelComment',
        ),
        migrations.DeleteModel(
            name='ReelLike',
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
            ],
            options={
                'verbose_name': 'Reel',
                'verbose_name_plural': 'Reels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.instagrampost',),
        ),
    ]
