# Generated by Django 4.2.7 on 2025-11-16 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='instagram_posts/images/', verbose_name='Post Rasmi')),
                ('caption', models.TextField(blank=True, max_length=2200, verbose_name='Sarlavha (Caption)')),
                ('hashtags', models.CharField(blank=True, help_text='Xeshteglarni vergul bilan ajrating (masalan: #django, #python, #instagram)', max_length=500)),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Joylashuv (Location Tag)')),
                ('post_type', models.CharField(choices=[('IMAGE', 'Yagona Rasm'), ('CAROUSEL', 'Karusel'), ('REEL', 'Reel (Video)')], default='IMAGE', max_length=10, verbose_name='Post Turi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan Sana')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Instagram Posti',
                'verbose_name_plural': 'Instagram Postlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
