# Generated by Django 5.2.8 on 2025-11-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='post_type',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='video',
            field=models.FileField(blank=True, upload_to='instagram_posts/videos/', verbose_name='Post Videosi'),
        ),
    ]
