# Generated by Django 5.2.8 on 2025-11-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_instagrampost_post_type_instagrampost_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='image',
            field=models.ImageField(blank=True, upload_to='instagram_posts/images/', verbose_name='Post Rasmi'),
        ),
    ]
