# Generated by Django 4.2.7 on 2025-11-23 11:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_instagrampost_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Instagram Post', 'verbose_name_plural': 'Instagram Postlari'},
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='post_type',
            field=models.CharField(choices=[('IMAGE', 'Rasm'), ('REEL', 'Reel (Video)'), ('CAROUSEL', 'Karusel')], default='IMAGE', max_length=10, verbose_name='Post Turi'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar"),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='caption',
            field=models.TextField(blank=True, max_length=2200, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='hashtags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_posts/images/%Y/%m/%d/', verbose_name='Post Rasmi'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='instagram_posts/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Post Videosi'),
        ),
    ]
